### ISSUE TITLE
composer require juliangut/slim-controller fails

### ISSUE THREAD

**Issue by tomshaw** [juliangut/slim-controller#1]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for juliangut/slim-controller ^1.4 -> satisfiable by juliangut/slim-controller[1.4].
    - juliangut/slim-controller 1.4 requires slim/slim 3.x-dev -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by juliangut** [comment]
Hello tomshaw,
First of all tell you that this package was created when Slim3.x was still in heavy development, since then it has been released but this package has not been updated, thus it points to a non-existent Slim version (3.x-dev)

Appart from that I strongly suggest you not to use this package, instead inject your controllers (and dependencies) explicitly in the container. This package was a proof of concept on how to autoregister class controllers on Slim and unless you plan to include an absurdly large number of controllers you can add them manually instead.

Any question you may have don't hesitate asking

**Comment by tomshaw** [comment]
Thanks. I was playing with slim for the first time over the weekend and stumbled upon your repository and thought that was a neat idea. I ended up simply creating an array to inject the controller dependencies explicitly in the [container.](https://github.com/tomshaw/directory/blob/master/app/dependencies.php) 

juliangut/slim-doctrine also worked perfectly. Thanks!
